class Bodies_lists {
  static List<String> body_templates = [
    "Additionaly, our life has gone through great changes SOMETHING came into being, which provides a totally new and different way of using our spare time to the traditional way",
    "Moreover, it is ADJ to DO SOMETHING WITH PEOPLE.",
    "Moreover, they could help us find the answers of many questions about the historical development of our society.",
    "SOMEONE/SOMETHING requires SOMEONE to V1",
    "Moreover, SOMETHING enable us to VERB",
    "It allows PEOPLE to DO",
    "SOMETHING offers PEOPLE NOUN to V1 SOMETHING.",
    "SOMETHING helps SOMEONE to V1.",
    "SOMETHING makes SOMEONE/NOUN ADJ",
    "SOMETHING is best way to V",
    "SOMEONE advised SOMENONE to DO",
    "SOMEONE commanded SOMEONE to DO.",
    "SOMEONE invited SOMEONE to DO SOMETHING.",
    "SOMEONE ordered SOMEONE to DO.",
    "SOMEONE persuade SOMEONE to DO",
    "SOMEONE told SOMEONE to DO",
    "SOMEONE urges SOMEONE to DO",
    "SOMEONE warns SOMEONE to DO",
    "SOMEONE reminds SOMEONE to DO",
    "SOMEONE encourages SOMEONE to DO",
    "SOMEONE expects SOMEONE to DO",
    "SOMEONE instructed SOMEONE to DO",
    "SOMEONE/SOMETHING causes SOMEONE to V1",
    "Have + object + verb",
    "Make + object + verb",
    "Let + object + verb",
    "Get + person + to + verb",
    "SOMETHING allows PEOPLE to DO ADV which enables them to DO",
    "SOMETHING did not only help SOMEONE V1, but also enabled SOMEONE to V1.",
    "SOMETHING fortifies SOMETHING, enhance SOMETHING, and broaden  SOMETHING. With those, we are more capable of DOING SOMETHING",
    "SOMETHING IS NEED TO V1 SOMETHING FOR AIM",
    "Something has made it possible to V1",
    "PEOPLE WHO V1 SOMETHING can/may V1 SOMETHING",
    "if PRESENT SIMPLE+ WILL/WON'T VERB",
    "if  PAST SIMPLE+ could/would V1",
    "IF PAST PERFECT+ WOULD HAVE+PAST PARTICLE",
    "NOUN+ VING   +   BE/V1",
    "noun+v3 + OBJ",
    "noun+to V1+OBJ",
    "noun+to be+V3",
    "NOUN+having+ V3",
    "NOUN+having been +V3",
    "Object+ is/am/are+ V3+ by + subject ",
    "Object+ has/have+ been+ V3+ by + subject",
    "Object+ was/were V3+ by + subject"
  ];

  static List body_ids = [
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
    "59",
    "60",
    "61",
    "62",
    "63",
    "64",
    "65",
    "66",
    "67",
    "68",
    "69",
    "70",
    "71",
    "72",
    "73",
    "74",
    "75",
    "76",
    "77",
    "78",
    "79",
    "80",
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88"
  ];

  static List body_descriptions = [
    "Additionaly, our life has gone through great changes SOMETHING came into being, which provides a totally new and different way of using our spare time to the traditional way",
    "Moreover, it is hard to work on hard issues with classmates.",
    "Moreover, they could help us find the answers of many questions about the historical development of our society.",
    "Some universities require students to choose a variety of subjects; others only require students to specialize in one subject.",
    "Moreover, the autos and highways enable us to enjoy the natural and quiet surroundings in the countryside.",
    "In addition, telephone allows us to communicate freely with the rest of the world.",
    "Group study offers students a chance to discuss the problems and exchange opinions with each other.",
    "Working in a group helps students to become more responsible, cooperative and thoughtful.",
    "In addition,money makes our life happy and comfortable",
    "Furthermore,living in a big city is the best way to make our lives enjoyable and worthwhile.",
    "My GP advised me to see a specialist.",
    "The colonel commanded his men to charge.",
    "I've invited Jill to come to dinner on Saturday.",
    "After days of pointless fighting, the general ordered the marines to withdraw.",
    "I tried to persuade them to stay, but they said they were too tired.",
    "The doctor told me to give up smoking.",
    "The opposition urged the government to take action immediately.",
    "The professor warned us to be diligent with our weekly assignments.",
    "I reminded Andy to bring a bottle of wine and some snacks.",
    "we encourage students to use their abilities",
    "You expects me to go there",
    "The teacher instructed the students to draw circle.",
    "Global warming has caused governments to take actions.",
    "Ali will have her homework prepared for next week",
    "Laws make people obey the rules.",
    "Parents should not let their kids watch violent movies",
    "Mark is so much in love with me, I can get him to do anything I want.",
    "Thus, exercising allows students to study more efficiently which enables them to get better grades.",
    "Hence, interacting with others did not only help me understand the subject better, but also enabled me to remember the relevant information for a longer period of time.",
    "A university education fortifies our values, enhance our skills, and broaden our horizons. With those, we are more capable of giving a hand to those who are in need of help than ever before.",
    "A university degree is need to find a job",
    "Enormous changes in materials and techniques of construction  have made it possible to enclose space with much greater ease and speed and with a minimum of material.",
    "People who stick to their way of life may sometimes feel lonely and isolated",
    "if it rains, i will study my lessons at home",
    "certainly, if i earned money more, i would go on a holiday",
    "Certainly, if had not played basketball at university, i would not have developed my communication skills.",
    "the person knocking at my door is here \n"
        "Children attending to universites are more successful in life",
    "Materials needed for the experiment \n "
        "The people employed in the factory \n",
    "People to vote in the general elections \n"
        "Workes to clean the house \n "
        "Trucks to carry the products \n "
        "Trains to transport the iron",
    "Food to be cooked for the wedding\n "
        "Drugs to be used\n "
        "The car to be tested",
    "Visitors having seen Antalya want to see the city again. \n"
        " People having retired with low salary have to work again. \n "
        "Players having chosen to go abroad want to return home. \n "
        "Students having gratuated from this school go abroad. \n"
        " Women having raised children while they working are facing some problems.",
    "Vegetables having been grown in this village \n"
        "Workers having been fired \n"
        "Commodities having been sold \n"
        " People having been accused of terrorism \n"
        " Scientist having been awarded the Nobel Prize",
    "In addition, 40 percent of American grain-fed beef cattle are fattened in farms.",
    "Every development in modern life has been the result of major technological changes.",
    "Pacific islanders are thought to have come from North America."
  ];
}
