class Introduction_listeleri {
  static List<String> categories = [
    "People DO SOMETHING for various reasons. Some people consider SOMETHING as a challenge and others take it as a new experience.",
    "Different people will give different responses to this question from their own characters, emotional concerns and even educational backgrounds. However, when it comes to me, I believe that SOMETHING is best WAY to do SOMETHING for the following reasons.",
    "SOMETHING has always been the one of the greatest wants of humankind. It has influenced almost every step that humankind has taken.",
    "SOMETHING have changed the way people live radically.",
    "It has been noticed that SOMETHING influences people's behavior. The influence appears in different forms such as the way of eating, the kind of food,and general attitudes.",
    "I do strongly support the statement that SVO",
    "I totally agree with the statement that SVO",
    "There are always good and bad consequences following SOMETHING. SOMETHING has served many needs of people.",
    "Some may choose to DO SOMETHING, while other DO OTHER THING. As far as I am concerned, I would like to DO SOMETHING because SOMETHING has more advantages than OTHER THING",
    "Some people believed that they DO SOMETHING BY DOING SOMETHING, whereas other people believed that OTHER THING. As for me, I would like to side with the former people.",
    "When it comes to the issue of the SOMETHING, some people suggest that PEOPLE SHOULD DO SOMETHING rather than OTHER THING, while others maintain the opposite view. As far as I am concerned, the former point carries more weight.",
    "Some people claim that DOING SOMETHING is a must for PEOPLE. Other people, however, argue that it should be up to PEOPLE to decide whether they need to go or not. As far as I am concerned, no matter whether PEOPLE like it or not, they must DO SOMETHING ",
    "Some people may believe that DOING SOMETHING should be optional, but I really disagree with them about it.",
    "SOMETHING is among the most important factors affecting the living conditions of people in the society.",
    "It is a common phenomenon and an indisputable fact that people DO SOMETHING",
    "There are both advantages and disadvantages of DOING SOMETHING WITH SOMEONE",
    "I think it's better for SOME PEOPLE to DO SOMETHING, and DO OTHER THINGS.",
    "Some people like to DO SOMETHING while others think that DOING OTHER THING is more enjoyable. To me, I choose DOING SOMETHING because it is ADJ for me",
    "With the help of SOMETHING PEOPLE can DO SOMETHING it more ADV. I agree with this statement.",
    "SOMETHING has been an issue broadly discussed and defined by different approaches. Some say that being SOMETHING means being SOMETHING. Others associate SOMETHING with OTHER THING.",
    "SOMETHING is a very pleasant thing. Some people like to DO. Other people, however, would prefer to DO. As far as I am concerned, DOING SOMETHING is better.",
    "Some people prefer to DO SOMETHING. Others, however, prefer to DO OTHER THINGS. As far as I am concerned, DOING SOMETHING is better because SVO,",
    "It is fair to state that SVO",
    "I am surely of the opinion that SVO",
    "SOMETHING is a common phenomenon each one of us undergoes in our daily life.",
    "Some people think that SOMETHING should DO an important role in the life. There are many arguments for and against both positions, but in my opinion everyone should DO it.",
    "Different people hold different opinions in SOMETHING. Some consider SOMETHING FIRST ARGUMENT; others regard OTHER ARGUMENT. As far as I am concerned, THESİS.",
    "Some people argue that SVO. I cannot agree with them more. There are numerous reasons why I hold confidence on this opinion, and I would explore only a few primary ones here.",
    "There are many advantages for people to DO SOMETHING for themselves and have their own business or personal life.",
    "I strongly agree that SVO",
    "Since V2, we can notice that there are a lot of changes happened around us.",
    "It is a well-established fact that SVO",
    "A lot of people claim that THESIS. I agree with this statement, because DEFENDING ARGUMENT.",
    "Almost in every modern society, SOMETHING plays an import role in daily life.",
    "Nowadays SOMETHING is becoming more and more popular. When it comes to THE PROBLEM, many people prefer to FIRST OPINION, while others may prefer OPPOSED OPINION. My viewpoint is both have advantages and disadvantages.",
    "Nowadays, some people may hold the opinion that SVO. As far as I am concerned, I agree that THESIS My arguments for this point are listed as follows.",
    "With SOMETHING, there have been a lot of changes to our life. Admittedly, some of these changes are bad, causing many BAD CONSEQUENCES. However, most of these changes contribute to making our life more convenient, more comfortable and more wonderful.",
    "Many people take the view that technology has made the world a better place to live. As far as I am concerned, I share the common view with them. Because I could pick up examples here and there around us and I would here explore a few of the most important ones.",
    "Nowadays some may hold the opinion that SVO. As far as I am concerned, I agree with this statement. My arguments for this point are listed as follows.",
    "SOMETHING plays an important role in modern society. SOMETHING covering every aspect of social life.",
    "People have different ways to DO SOMETHING. Some people DO SOMETHING; other people COUNTER ARGUMENT. As far as I am concerned, the first method -SOMETHING is suitable for me. The reasons are as follows.",
    "Most people agree that SVO. In my opinion THESIS STATEMENT. I feel this way for two reasons, which I will explore in the following essay.",
    "It is critically important that SVO. In my opinion,THESIS STATEMENT.  I feel this way for two main reasons, which I will explore in the following essay.",
  ];

  static List idler = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
  ];

  static List descriptions = [
    "People go abroad for various reasons. Some people consider going abroad as a challenge and others take it as a new experience. In my opinion, people go abroad to increase their knowledge about world, meet new people and develop a career.",
    "Different people will give different responses to this question from their own characters, emotional concerns and even educational backgrounds. However, when it comes to me, I believe that daily homework is the best way for students to review what they learned during the day",
    "Earning money has always been the one of the greatest wants of humankind. It has influenced almost every step that humankind has taken.",
    "Recent technological advancements have changed the way people live radically.",
    "It has been noticed that living in a big city influences people's behavior. The influence appears in different forms such as the way of eating, the kind of food,and general attitudes.",
    "I do strongly support the statement that people behave differently when they wear different clothes.",
    "I totally agree with the statement that all students should be required to study art and music in secondary schools.",
    "There are always good and bad consequences following technological developments. They have served many needs of people.",
    "Some may choose to live in big cities, while other like the natural and quiet surroundings in the countryside. As far as I am concerned, I would like to live in a big city because living in a big city has more advantages than living in the countryside",
    "Some people believed that they achieved success by their own ability, whereas other people believed that they did it by luck. As for me, I would like to side with the former people. I am willing to discuss it by proposing two main reasons.",
    "When it comes to the issue of the arrangement of the university budget, some people suggest that universities should spend more money on their libraries rather than on student's sports activities, while others maintain the opposite view. As far as I am concerned, the former point carries more weight. I take this view on account of the following reasons. ",
    "Some people claim that attending classes is a must to students. Other people, however, argue that it should be up to the students to decide whether they need to go or not. As far as I am concerned, no matter whether students like it or not, they must attend classes. ",
    "Some people may believe that going to classes should be optional, but I really disagree with them about it.",
    "Transportation is among the most important factors affecting the living conditions of people in the society.",
    "It is a common phenomenon and an indisputable fact that people are spending much more money in these days.",
    "There are both advantages and disadvantages of establishing a shopping mall in our neighborhood.",
    "I think it's better for college students to live on-campus during their first two years in college, and then move into an apartment off-campus during their last two years.",
    "Some people like to attend a live performance while others think that watching the same event on television is more enjoyable. To me, I choose watching an event on television because it is easier.",
    "With the help of technology students nowadays can learn more information and learn it more quickly.I agree with this statement.",
    "Success has been an issue broadly discussed and defined by different approaches. Some say that being successful means being wealthy. Others associate success with popularity and power. A third approach would relate success with social and emotional well-being.",
    "Traveling is a very pleasant thing. Some people like to travel with several friends. Other people, however, would prefer to travel alone. As far as I am concerned, traveling with my friends is better.",
    "Some people prefer to get up early in the morning and start the day's work. Others, however, prefer to get up later in the day and work until late at night. As far as I am concerned, getting up early is a good habit because it is good for health, and it is easy for people to take care of everyday work.",
    "It is fair to state that people want to live longer",
    "I am surely of the opinion that physical exercise should be a required part of every school day",
    "Decision-making is a common phenomenon each one of us undergoes in our daily life.",
    "Some people think that games should play an important role in the life of everyone including adults; others think that games should be left for children. There are many arguments for and against both positions, but in my opinion everyone should have a hobby and playing games is good.",
    "Different people hold different opinions in choosing friends. Some consider intelligence as the most important characteristics in their friends; others regard a sense of humor as the most significant personality. As far as I am concerned, reliability, which means faith, confidence and trust, is of vital importance.",
    "Some people argue that most experiences in our lives that seemed difficult at the time, can later become valuable experiences. I cannot agree with them more. There are numerous reasons why I hold confidence on this opinion, and I would explore only a few primary ones here.",
    "There are many advantages for people to work for themselves and have their own business.",
    "I strongly agree that classmates are more influential to a child's success at school than parents",
    "Since the first automobile was introduced to our life, we can notice that there are a lot of changes happened around us.",
    "It is a well-established fact that automobiles have contributed to the modern life in a favorable way",
    "A lot of people claim that marks in tests encourage students to learn. I agree with this statement, because examinations are a good way for a student to review what he/she has learned; test scores are a standard measurement for students' learning ability and knowledge level; and the test system can benefit students' future.",
    "Almost in every modern society, grades play an import role in assessing students' academic ability",
    "Nowadays traveling is becoming more and more popular, as we have more leisure time and more money to spend during our vacations. When it comes to ways of traveling, many people prefer to join groups arranged by travel services and escorted by tour guides, while others may argue independent backpack travel should be better. My viewpoint is both have advantages and disadvantages.",
    "Nowadays, some people may hold the opinion that boys and girls should attend separate schools, while others have a negative attitude. As far as I am concerned, I agree that boys and girls should go to separate schools. My arguments for this point are listed as follows.",
    "With the development of technology, there have been a lot of changes to our life. Admittedly, some of these changes are bad, causing many environmental and social problems. However, most of these changes contribute to making our life more convenient, more comfortable and more wonderful.",
    "Many people take the view that technology has made the world a better place to live. As far as I am concerned, I share the common view with them. Because I could pick up examples here and there around us and I would here explore a few of the most important ones.",
    "Nowadays some may hold the opinion that advertising can tell you a lot about a country. As far as I am concerned, I agree with this statement. My arguments for this point are listed as follows.",
    "Advertising plays an important role in modern society. Advertisements covering every aspect of social life can tell a lot about a country by the marriage of substantial information and colorful expressive forms.",
    "People have different ways to learn knowledge. Some people learn by doing things; other people learn by reading books; others learn by listening to people talk about things. As far as I am concerned, the first method - learning by doing is suitable for me. The reasons are as follows.",
    "Most people agree that  books and practice are important in the process of learning.  In my opinion, practices are more important than books. I feel this way for two reasons, which I will explore in the following essay",
    "It is critically important that books and practice are important in the process of learning. In my opinion,practices are more important than books.  I feel this way for two main reasons, which I will explore in the following essay.",
  ];
}
